//! `:Magit NAME`: upstream command names for Fred's actions, so commands
//! reached through M-x in Emacs (and every menu) have a way in.
use super::Action::{self, *};
use super::{Fold, apply, diff, log, misc, refs};

/// The action for an upstream command name.
pub fn by_name(name: &str) -> Option<Action> {
    let menu = |c| Some(Menu(c));
    match name {
        "magit" | "magit-status" | "magit-status-quick" | "magit-status-here" => Some(Status),
        "magit-dispatch" => menu('*'),
        "magit-branch" => menu('b'),
        "magit-branch-configure" => menu('c'),
        "magit-commit" => menu('C'),
        "magit-diff" => menu('d'),
        "magit-diff-refresh" => menu('D'),
        "magit-fetch" => menu('f'),
        "magit-pull" => menu('P'),
        "magit-push" => menu('p'),
        "magit-log" => menu('l'),
        "magit-shortlog" => menu('S'),
        "magit-merge" => menu('M'),
        "magit-rebase" => menu('r'),
        "magit-cherry-pick" => menu('x'),
        "magit-revert" => menu('v'),
        "magit-reset" => menu('X'),
        "magit-remote" => menu('O'),
        "magit-remote-configure" => menu('e'),
        "magit-stash" => menu('z'),
        "magit-stash-push" => menu('Q'),
        "magit-tag" => menu('t'),
        "magit-notes" => menu('N'),
        "magit-bisect" => menu('G'),
        "magit-worktree" => menu('Y'),
        "magit-submodule" => menu('o'),
        "magit-subtree" => menu('u'),
        "magit-subtree-import" => menu('I'),
        "magit-subtree-export" => menu('E'),
        "magit-patch" => menu('W'),
        "magit-patch-create" => menu('K'),
        "magit-patch-apply" => menu('a'),
        "magit-am" => menu('w'),
        "magit-bundle" => menu('J'),
        "magit-bundle-create" => menu('j'),
        "magit-clone" => menu('k'),
        "magit-show-refs" => menu('y'),
        "magit-gitignore" => menu('g'),
        "magit-sparse-checkout" => menu('>'),
        "magit-file-dispatch" => menu('F'),
        "magit-blame" => menu('B'),
        "magit-init" => Some(Init),
        "magit-commit-create" => Some(Commit),
        "magit-commit-amend" => Some(AmendDraft),
        "magit-commit-reword" => Some(RewordDraft),
        "magit-log-current" => Some(Log),
        "magit-log-head" => Some(LogHead),
        "magit-log-buffer-file" => Some(FileLog),
        "magit-log-other" => Some(LogOp(log::Op::Other)),
        "magit-log-related" => Some(LogOp(log::Op::Related)),
        "magit-log-branches" => Some(LogOp(log::Op::LocalBranches)),
        "magit-log-all-branches" => Some(LogOp(log::Op::AllBranches)),
        "magit-log-all" => Some(LogOp(log::Op::All)),
        "magit-log-reflog" => Some(LogOp(log::Op::Reflog)),
        "magit-log-merged" => Some(LogOp(log::Op::Merged)),
        "magit-cherry" => Some(LogOp(log::Op::Cherry)),
        "magit-reflog-current" => Some(Reflog(Some(String::new()))),
        "magit-reflog-head" => Some(Reflog(Some("HEAD".into()))),
        "magit-reflog-other" => Some(Reflog(None)),
        "magit-diff-dwim" => Some(Diff(diff::Op::Dwim)),
        "magit-diff-range" => Some(Diff(diff::Op::Range)),
        "magit-diff-paths" => Some(Diff(diff::Op::Paths)),
        "magit-diff-unstaged" => Some(Diff(diff::Op::Unstaged)),
        "magit-diff-staged" => Some(Diff(diff::Op::Staged)),
        "magit-diff-working-tree" => Some(Diff(diff::Op::Worktree)),
        "magit-show-commit" => Some(Diff(diff::Op::ShowCommit)),
        "magit-stash-show" => Some(Diff(diff::Op::ShowStash)),
        "magit-diff-buffer-file" => Some(DiffBufferFile),
        "magit-diff-while-committing" => Some(DiffWhileCommitting),
        "magit-stash-list" => Some(Stashes),
        "magit-show-refs-head" => Some(Refs(refs::Op::Head)),
        "magit-show-refs-current" => Some(Refs(refs::Op::Current)),
        "magit-show-refs-other" => Some(Refs(refs::Op::Other)),
        "magit-find-file" => Some(FindFile),
        "magit-refresh" => Some(Refresh),
        "magit-refresh-all" => Some(RefreshAll),
        "magit-stage-modified" => Some(ApplyOp(apply::Kind::StageModified)),
        "magit-unstage-all" => Some(ApplyOp(apply::Kind::UnstageAll)),
        "magit-discard" => Some(ApplyOp(apply::Kind::Discard)),
        "magit-reverse" => Some(ApplyOp(apply::Kind::Reverse)),
        "magit-fetch-all-prune" => Some(GitRun(&["remote", "update", "--prune"])),
        "magit-fetch-all-no-prune" => Some(GitRun(&["remote", "update"])),
        // magit-push-implicitly: git push -v with no refspec.
        "magit-push-implicitly" => Some(GitRun(&["push", "-v"])),
        "magit-run" => menu('!'),
        "magit-log-trace-definition" => Some(TraceDefinition),
        "magit-edit-line-commit" => Some(EditLineCommit),
        "magit-display-repository-buffer" | "magit-switch-to-repository-buffer" => Some(Status),
        "magit-git-command" => Some(Misc(misc::Op::GitCommand { topdir: false })),
        "magit-git-command-topdir" => Some(Misc(misc::Op::GitCommand { topdir: true })),
        "magit-reset-quickly" => Some(Misc(misc::Op::ResetQuickly)),
        "magit-remote-set-head" => Some(Misc(misc::Op::RemoteSetHead)),
        "magit-remote-unset-head" => Some(Misc(misc::Op::RemoteUnsetHead)),
        "magit-section-show-level-1-all" => Some(Fold(Fold::Level(1))),
        "magit-section-show-level-2-all" => Some(Fold(Fold::Level(2))),
        "magit-section-show-level-3-all" => Some(Fold(Fold::Level(3))),
        "magit-section-show-level-4-all" => Some(Fold(Fold::Level(4))),
        _ => None,
    }
}
