//! `:Magit NAME`: upstream command names for Fred's actions, so commands
//! reached through M-x in Emacs (and every menu) have a way in.
use super::Action::{self, *};
use super::{Fold, apply, diff, ediff, log, misc, refs, wip};

/// The action for an upstream command name.
pub fn by_name(name: &str) -> Option<Action> {
    let menu = |c| Some(Menu(c));
    match name {
        "magit" | "magit-status" | "magit-status-quick" | "magit-status-here" => Some(Status),
        "magit-dispatch" => menu('*'),
        "magit-branch" => menu('b'),
        "magit-branch-configure" => menu('c'),
        "magit-commit" => menu('C'),
        "magit-diff" => menu('d'),
        "magit-diff-refresh" => menu('D'),
        "magit-fetch" => menu('f'),
        "magit-pull" => menu('P'),
        "magit-push" => menu('p'),
        "magit-log" => menu('l'),
        "magit-shortlog" => menu('S'),
        "magit-merge" => menu('M'),
        "magit-rebase" => menu('r'),
        "magit-cherry-pick" => menu('x'),
        "magit-revert" => menu('v'),
        "magit-reset" => menu('X'),
        "magit-remote" => menu('O'),
        "magit-remote-configure" => menu('e'),
        "magit-stash" => menu('z'),
        "magit-stash-push" => menu('Q'),
        "magit-tag" => menu('t'),
        "magit-notes" => menu('N'),
        "magit-bisect" => menu('G'),
        "magit-worktree" => menu('Y'),
        "magit-submodule" => menu('o'),
        "magit-subtree" => menu('u'),
        "magit-subtree-import" => menu('I'),
        "magit-subtree-export" => menu('E'),
        "magit-patch" => menu('W'),
        "magit-patch-create" => menu('K'),
        "magit-patch-apply" => menu('a'),
        "magit-am" => menu('w'),
        "magit-bundle" => menu('J'),
        "magit-bundle-create" => menu('j'),
        "magit-clone" => menu('k'),
        "magit-show-refs" => menu('y'),
        "magit-gitignore" => menu('g'),
        "magit-sparse-checkout" => menu('>'),
        "magit-file-dispatch" => menu('F'),
        "magit-blame" => menu('B'),
        "magit-init" => Some(Init),
        "magit-commit-create" => Some(Commit),
        "magit-commit-absorb" => menu('A'),
        "magit-commit-autofixup" => menu('H'),
        "magit-commit-amend" => Some(AmendDraft),
        "magit-commit-reword" => Some(RewordDraft),
        "magit-log-current" => Some(Log),
        "magit-log-head" => Some(LogHead),
        "magit-log-buffer-file" => Some(FileLog),
        "magit-log-other" => Some(LogOp(log::Op::Other)),
        "magit-log-related" => Some(LogOp(log::Op::Related)),
        "magit-log-branches" => Some(LogOp(log::Op::LocalBranches)),
        "magit-log-all-branches" => Some(LogOp(log::Op::AllBranches)),
        "magit-log-all" => Some(LogOp(log::Op::All)),
        "magit-log-reflog" => Some(LogOp(log::Op::Reflog)),
        "magit-log-merged" => Some(LogOp(log::Op::Merged)),
        "magit-cherry" => Some(LogOp(log::Op::Cherry)),
        "magit-reflog-current" => Some(Reflog(Some(String::new()))),
        "magit-reflog-head" => Some(Reflog(Some("HEAD".into()))),
        "magit-reflog-other" => Some(Reflog(None)),
        "magit-diff-dwim" => Some(Diff(diff::Op::Dwim)),
        "magit-diff-range" => Some(Diff(diff::Op::Range)),
        "magit-diff-paths" => Some(Diff(diff::Op::Paths)),
        "magit-diff-unstaged" => Some(Diff(diff::Op::Unstaged)),
        "magit-diff-staged" => Some(Diff(diff::Op::Staged)),
        "magit-diff-working-tree" => Some(Diff(diff::Op::Worktree)),
        "magit-show-commit" => Some(Diff(diff::Op::ShowCommit)),
        "magit-stash-show" => Some(Diff(diff::Op::ShowStash)),
        "magit-diff-buffer-file" => Some(DiffBufferFile),
        "magit-diff-while-committing" => Some(DiffWhileCommitting),
        "magit-stash-list" => Some(Stashes),
        "magit-show-refs-head" => Some(Refs(refs::Op::Head)),
        "magit-show-refs-current" => Some(Refs(refs::Op::Current)),
        "magit-show-refs-other" => Some(Refs(refs::Op::Other)),
        "magit-find-file" | "magit-find-file-other-window" | "magit-find-file-other-frame" => {
            Some(FindFile)
        }
        "magit-refresh" => Some(Refresh),
        "magit-refresh-all" => Some(RefreshAll),
        "magit-stage-modified" => Some(ApplyOp(apply::Kind::StageModified)),
        "magit-unstage-all" => Some(ApplyOp(apply::Kind::UnstageAll)),
        "magit-discard" => Some(ApplyOp(apply::Kind::Discard)),
        "magit-reverse" => Some(ApplyOp(apply::Kind::Reverse)),
        "magit-reverse-in-index" => Some(ReverseInIndex),
        "magit-stage-files" => Some(Misc(misc::Op::StageFiles(false))),
        "magit-margin-settings" => menu('L'),
        "magit-shell-command" => Some(Misc(misc::Op::ShellCommand { topdir: false })),
        "magit-shell-command-topdir" => Some(Misc(misc::Op::ShellCommand { topdir: true })),
        "magit-run-gitk" => Some(Misc(misc::Op::Gitk(""))),
        "magit-run-gitk-all" => Some(Misc(misc::Op::Gitk("--all"))),
        "magit-run-gitk-branches" => Some(Misc(misc::Op::Gitk("--branches"))),
        "magit-run-git-gui" => Some(Misc(misc::Op::GitGui)),
        "magit-run-git-gui-blame" => Some(GitGuiBlame),
        "magit-debug-git-executable" => Some(Misc(misc::Op::DebugGit)),
        "magit-abort-dwim" => Some(AbortDwim),
        "magit-edit-thing" => Some(Thing('e')),
        "magit-browse-thing" => Some(Thing('o')),
        "magit-copy-thing" => Some(Thing('w')),
        "magit-info" => Some(Info),
        "magit-auto-revert-mode" => Some(AutoRevertMode),
        "magit-dired-am-apply-patches" => Some(DiredAm),
        "magit-do-async-shell-command" => Some(AsyncShell),
        "magit-ediff-stage" => Some(EdiffStage),
        "magit-update-index" => Some(UpdateIndex),
        "magit-wip-commit-buffer-file" => Some(WipCommitFile),
        "magit-wip-mode" => Some(WipMode),
        "magit-toggle-git-debug" => Some(DebugToggle('d')),
        "magit-toggle-subprocess-record" => Some(DebugToggle('r')),
        "magit-toggle-profiling" => Some(DebugToggle('p')),
        "magit-toggle-verbose-refresh" => Some(DebugToggle('v')),
        "magit-profile-refresh-buffer" => Some(ProfileRefresh),
        "magit-zap-caches" => Some(ZapCaches),
        "magit-save-repository-buffers" => Some(SaveRepositoryBuffers),
        "magit-project-status" => Some(Status),
        "magit-project-dispatch" => menu('*'),
        "magit-next-reference" => Some(NextReference(false)),
        "magit-previous-reference" => Some(NextReference(true)),
        "magit-log-move-to-revision" => Some(LogMoveTo),
        "magit-section-cycle-diffs" => Some(CycleDiffs),
        "magit-go-backward" => Some(Go(true)),
        "magit-go-forward" => Some(Go(false)),
        "magit-describe-section" => Some(DescribeSection(true)),
        "magit-describe-section-briefly" => Some(DescribeSection(false)),
        "magit-show-commit-removing-file" => Some(Misc(misc::Op::RemovingFile)),
        "magit-toggle-margin" => Some(Margin('L')),
        "magit-cycle-margin-style" => Some(Margin('l')),
        "magit-toggle-margin-details" => Some(Margin('d')),
        "magit-toggle-log-margin-style" => Some(Margin('x')),
        "magit-toggle-buffer-lock" => Some(BufferLock),
        "magit-diff-toggle-refine-hunk" => Some(DiffToggle('t')),
        "magit-diff-toggle-fontify-hunk" => Some(DiffToggle('T')),
        "git-commit-save-message" => Some(SaveMessage),
        "git-commit-insert-changelog-gnu" | "magit-generate-changelog" => Some(Changelog(true)),
        "git-commit-insert-changelog-plain" => Some(Changelog(false)),
        "magit-commit-add-log" => Some(CommitAddLog),
        "magit-add-change-log-entry" | "magit-add-change-log-entry-other-window" => {
            Some(AddChangeLogEntry)
        }
        "magit-unstage-files" => Some(Misc(misc::Op::UnstageFiles)),
        "magit-copy-diff-as-kill" => Some(CopyDiff),
        "magit-fetch-all-prune" => Some(GitRun(&["remote", "update", "--prune"])),
        "magit-fetch-all-no-prune" => Some(GitRun(&["remote", "update"])),
        // magit-push-implicitly: git push -v with no refspec.
        "magit-push-implicitly" => Some(GitRun(&["push", "-v"])),
        "magit-run" => menu('!'),
        "magit-process-buffer" => Some(ProcessBuffer),
        "magit-delete-shelved-branch" => Some(super::Action::Configure(
            super::configure::Op::DeleteShelved,
        )),
        "magit-push-notes-ref" => {
            Some(super::Action::Configure(super::configure::Op::PushNotesRef))
        }
        "magit-revision-jump" | "magit-jump-to-revision-headers" => Some(RevisionJump("headers")),
        "magit-jump-to-revision-message" => Some(RevisionJump("message")),
        "magit-jump-to-revision-notes" => Some(RevisionJump("notes")),
        "magit-jump-to-revision-diffstat" => Some(RevisionJump("diffstat")),
        "magit-jump-to-revision-diff" => Some(RevisionJump("diff")),
        "magit-blame-visit-file" => Some(BlameVisitFile),
        "magit-log-half-commit-limit" => Some(LogHalfLimit),
        "magit-version" => Some(Version),
        "magit-branch-or-checkout" => Some(super::Action::Branch(super::branch::Op::OrCheckout)),
        "magit-checkout-remote-ref" => Some(super::Action::Branch(super::branch::Op::RemoteRef)),
        "magit-update-default-branch" => {
            Some(super::Action::Branch(super::branch::Op::UpdateDefault))
        }
        "magit-pull-into-upstream" => Some(Net(super::network::Op::PullIntoUpstream)),
        "magit-push-to-remote" => Some(Net(super::network::Op::PushToRemote)),
        "magit-dired-jump" => Some(DiredJump),
        "magit-dired-stage" => Some(File(super::blob::FileOp::Stage)),
        "magit-dired-unstage" => Some(File(super::blob::FileOp::Unstage)),
        "magit-dired-log" => Some(FileLog),
        "magit-ediff" => menu('U'),
        "magit-ediff-dwim" => Some(EdiffDwim),
        "magit-ediff-resolve-rest" | "magit-ediff-resolve-all" | "magit-git-mergetool" => {
            Some(Ediff(ediff::Op::Resolve))
        }
        "magit-ediff-show-unstaged" => Some(Ediff(ediff::Op::ShowUnstaged)),
        "magit-ediff-show-staged" => Some(Ediff(ediff::Op::ShowStaged)),
        "magit-ediff-show-working-tree" => Some(Ediff(ediff::Op::ShowWorktree)),
        "magit-ediff-show-commit" => Some(Ediff(ediff::Op::ShowCommit)),
        "magit-ediff-compare" => Some(Ediff(ediff::Op::Compare)),
        "magit-ediff-show-stash" => Some(Ediff(ediff::Op::ShowStash)),
        "magit-diff-unmerged" => Some(DiffUnmerged),
        "magit-diff-toggle-file-filter" => Some(DiffRefresh(diff::Refresh::FileFilter)),
        "magit-clean" => Some(Misc(misc::Op::Clean(0))),
        "magit-clean-ignored" => Some(Misc(misc::Op::Clean(1))),
        "magit-find-git-config-file"
        | "magit-find-git-config-file-other-window"
        | "magit-find-git-config-file-other-frame" => Some(Misc(misc::Op::GitConfigFile)),
        "git-commit-co-authored" => Some(Trailer("Co-authored-by")),
        "git-commit-co-developed" => Some(Trailer("Co-developed-by")),
        "git-commit-ack" => Some(Trailer("Acked-by")),
        "git-commit-review" => Some(Trailer("Reviewed-by")),
        "git-commit-signoff" => Some(Trailer("Signed-off-by")),
        "git-commit-test" => Some(Trailer("Tested-by")),
        "git-commit-cc" => Some(Trailer("Cc")),
        "git-commit-reported" => Some(Trailer("Reported-by")),
        "git-commit-suggested" => Some(Trailer("Suggested-by")),
        "git-commit-modified" => Some(Trailer("Modified-by")),
        "magit-log-refresh" => menu('R'),
        "magit-wip-commit" => Some(Wip(wip::Op::Commit)),
        "magit-wip-log-index" => Some(Wip(wip::Op::LogIndex)),
        "magit-wip-log-worktree" => Some(Wip(wip::Op::LogWorktree)),
        "magit-wip-log-current" | "magit-wip-log" => Some(Wip(wip::Op::LogCurrent)),
        "magit-wip-purge" => Some(Wip(wip::Op::Purge)),
        "magit-status-jump" => menu('h'),
        "magit-parent-status" => Some(ParentStatus),
        "magit-jump-to-stashes" => Some(Jump("Stashes")),
        "magit-jump-to-tracked" => Some(Jump("Tracked files")),
        "magit-jump-to-untracked" => Some(Jump("Untracked files")),
        "magit-jump-to-ignored" => Some(Jump("Ignored files")),
        "magit-jump-to-unstaged" => Some(Jump("Unstaged changes")),
        "magit-jump-to-staged" => Some(Jump("Staged changes")),
        "magit-jump-to-assume-unchanged" => Some(Jump("Assume-unchanged files")),
        "magit-jump-to-skip-worktree" => Some(Jump("Skip-worktree files")),
        "magit-log-trace-definition" => Some(TraceDefinition),
        "magit-edit-line-commit" => Some(EditLineCommit),
        "magit-display-repository-buffer" | "magit-switch-to-repository-buffer" => Some(Status),
        "magit-git-command" => Some(Misc(misc::Op::GitCommand { topdir: false })),
        "magit-git-command-topdir" => Some(Misc(misc::Op::GitCommand { topdir: true })),
        "magit-reset-quickly" => Some(Misc(misc::Op::ResetQuickly)),
        "magit-remote-set-head" => Some(Misc(misc::Op::RemoteSetHead)),
        "magit-remote-unset-head" => Some(Misc(misc::Op::RemoteUnsetHead)),
        "magit-section-show-level-1-all" => Some(Fold(Fold::Level(1))),
        "magit-section-show-level-2-all" => Some(Fold(Fold::Level(2))),
        "magit-section-show-level-3-all" => Some(Fold(Fold::Level(3))),
        "magit-section-show-level-4-all" => Some(Fold(Fold::Level(4))),
        _ => None,
    }
}
