//! Upstream keymaps (generated from docs/org-keys.csv by the inventory).
//! Emacs key descriptions; `<remap>`, menu-bar, mouse and ESC-prefixed
//! duplicates of Meta keys are left out.

pub const ORG_MODE_MAP: &[(&str, &str)] = &[
    ("C-#", "org-table-rotate-recalc-marks"),
    ("C-j", "org-return-and-maybe-indent"),
    ("RET", "org-return"),
    ("C-'", "org-cycle-agenda-files"),
    ("C-,", "org-cycle-agenda-files"),
    ("C-S-<return>", "org-insert-todo-heading-respect-content"),
    ("C-<return>", "org-insert-heading-respect-content"),
    ("|", "org-force-self-insert"),
    ("C-x n e", "org-narrow-to-element"),
    ("C-x n b", "org-narrow-to-block"),
    ("C-x n s", "org-narrow-to-subtree"),
    ("C-S-<down>", "org-shiftcontroldown"),
    ("C-S-<up>", "org-shiftcontrolup"),
    ("C-S-<left>", "org-shiftcontrolleft"),
    ("C-S-<right>", "org-shiftcontrolright"),
    ("S-<right>", "org-shiftright"),
    ("S-<left>", "org-shiftleft"),
    ("S-<down>", "org-shiftdown"),
    ("S-<up>", "org-shiftup"),
    ("M-S-<down>", "org-shiftmetadown"),
    ("M-S-<up>", "org-shiftmetaup"),
    ("M-S-<right>", "org-shiftmetaright"),
    ("M-S-<left>", "org-shiftmetaleft"),
    ("C-M-S-<left>", "org-decrease-number-at-point"),
    ("C-M-S-<right>", "org-increase-number-at-point"),
    ("M-<down>", "org-metadown"),
    ("M-<up>", "org-metaup"),
    ("M-<right>", "org-metaright"),
    ("M-<left>", "org-metaleft"),
    ("M-S-<return>", "org-insert-todo-heading"),
    ("S-RET", "org-table-copy-down"),
    ("S-<return>", "org-table-copy-down"),
    ("<backtab>", "org-shifttab"),
    ("S-TAB", "org-shifttab"),
    ("M-h", "org-mark-element"),
    ("M-{", "org-backward-element"),
    ("M-}", "org-forward-element"),
    ("C-M-t", "org-transpose-element"),
    ("M-RET", "org-meta-return"),
    ("M-S-RET", "org-insert-todo-heading"),
    ("TAB", "org-cycle"),
    ("C-c C-v C-M-h", "org-babel-mark-block"),
    ("C-c C-v k", "org-babel-remove-result-one-or-many"),
    ("C-c C-v x", "org-babel-do-key-sequence-in-edit-buffer"),
    ("C-c C-v C-x", "org-babel-do-key-sequence-in-edit-buffer"),
    ("C-c C-v h", "org-babel-describe-bindings"),
    ("C-c C-v a", "org-babel-sha1-hash"),
    ("C-c C-v C-a", "org-babel-sha1-hash"),
    ("C-c C-v z", "org-babel-switch-to-session-with-code"),
    ("C-c C-v C-z", "org-babel-switch-to-session"),
    ("C-c C-v I", "org-babel-view-src-block-info"),
    ("C-c C-v i", "org-babel-lob-ingest"),
    ("C-c C-v TAB", "org-babel-view-src-block-info"),
    ("C-c C-v l", "org-babel-load-in-session"),
    ("C-c C-v C-l", "org-babel-load-in-session"),
    ("C-c C-v j", "org-babel-insert-header-arg"),
    ("C-c C-v C-j", "org-babel-insert-header-arg"),
    ("C-c C-v c", "org-babel-check-src-block"),
    ("C-c C-v C-c", "org-babel-check-src-block"),
    ("C-c C-v f", "org-babel-tangle-file"),
    ("C-c C-v C-f", "org-babel-tangle-file"),
    ("C-c C-v t", "org-babel-tangle"),
    ("C-c C-v C-t", "org-babel-tangle"),
    ("C-c C-v d", "org-babel-demarcate-block"),
    ("C-c C-v C-d", "org-babel-demarcate-block"),
    ("C-c C-v s", "org-babel-execute-subtree"),
    ("C-c C-v C-s", "org-babel-execute-subtree"),
    ("C-c C-v b", "org-babel-execute-buffer"),
    ("C-c C-v C-b", "org-babel-execute-buffer"),
    ("C-c C-v C-r", "org-babel-goto-named-result"),
    ("C-c C-v r", "org-babel-goto-named-result"),
    ("C-c C-v g", "org-babel-goto-named-src-block"),
    ("C-c C-v C-u", "org-babel-goto-src-block-head"),
    ("C-c C-v u", "org-babel-goto-src-block-head"),
    ("C-c C-v v", "org-babel-expand-src-block"),
    ("C-c C-v C-v", "org-babel-expand-src-block"),
    ("C-c C-v C-o", "org-babel-open-src-block-result"),
    ("C-c C-v o", "org-babel-open-src-block-result"),
    ("C-c C-v C-e", "org-babel-execute-maybe"),
    ("C-c C-v e", "org-babel-execute-maybe"),
    ("C-c C-v C-n", "org-babel-next-src-block"),
    ("C-c C-v n", "org-babel-next-src-block"),
    ("C-c C-v C-p", "org-babel-previous-src-block"),
    ("C-c C-v p", "org-babel-previous-src-block"),
    ("C-c C-,", "org-insert-structure-template"),
    ("C-c C-*", "org-list-make-subtree"),
    ("C-c @", "org-mark-subtree"),
    ("C-c :", "org-toggle-fixed-width"),
    ("C-c C-e", "org-export-dispatch"),
    ("C-c {", "org-table-toggle-formula-debugger"),
    ("C-c }", "org-table-toggle-coordinate-overlays"),
    ("C-c C-a", "org-attach"),
    ("C-c ~", "org-table-create-with-table.el"),
    ("C-c |", "org-table-create-or-convert-from-region"),
    ("C-c \" g", "org-plot/gnuplot"),
    ("C-c \" a", "orgtbl-ascii-plot"),
    ("C-c `", "org-table-edit-field"),
    ("C-c '", "org-edit-special"),
    ("C-c =", "org-table-eval-formula"),
    ("C-c +", "org-table-sum"),
    ("C-c ?", "org-table-field-info"),
    ("C-c #", "org-update-statistics-cookies"),
    ("C-c C-k", "org-kill-note-or-show-branches"),
    ("C-c C-c", "org-ctrl-c-ctrl-c"),
    ("C-c ^", "org-sort"),
    ("C-c TAB", "org-ctrl-c-tab"),
    ("C-c *", "org-ctrl-c-star"),
    ("C-c -", "org-ctrl-c-minus"),
    ("C-c ]", "org-remove-file"),
    ("C-c [", "org-agenda-file-to-front"),
    ("C-c <", "org-date-from-calendar"),
    ("C-c >", "org-goto-calendar"),
    ("C-c C-y", "org-evaluate-time-range"),
    ("C-c ,", "org-priority"),
    ("C-c !", "org-timestamp-inactive"),
    ("C-c .", "org-timestamp"),
    ("C-c C-z", "org-add-note"),
    ("C-c &", "org-mark-ring-goto"),
    ("C-c %", "org-mark-ring-push"),
    ("C-c C-o", "org-open-at-point"),
    ("C-c C-l", "org-insert-link"),
    ("C-c RET", "org-ctrl-c-ret"),
    ("C-c \\", "org-match-sparse-tree"),
    ("C-c /", "org-sparse-tree"),
    ("C-c C-w", "org-refile"),
    ("C-c ;", "org-toggle-comment"),
    ("C-c C-d", "org-deadline"),
    ("C-c C-s", "org-schedule"),
    ("C-c C-q", "org-set-tags-command"),
    ("C-c C-t", "org-todo"),
    ("C-c C-j", "org-goto"),
    ("C-c $", "org-archive-subtree"),
    ("C-c C-M-l", "org-insert-all-links"),
    ("C-c M-l", "org-insert-last-stored-link"),
    ("C-c C-M-w", "org-refile-reverse"),
    ("C-c M-w", "org-refile-copy"),
    ("C-c M-b", "org-previous-block"),
    ("C-c M-f", "org-next-block"),
    ("C-c C-b", "org-backward-heading-same-level"),
    ("C-c C-f", "org-forward-heading-same-level"),
    ("C-c C-_", "org-down-element"),
    ("C-c C-^", "org-up-element"),
    ("C-c C-r", "org-fold-reveal"),
    ("C-c <right>", "org-shiftright"),
    ("C-c <left>", "org-shiftleft"),
    ("C-c <down>", "org-shiftdown"),
    ("C-c <up>", "org-shiftup"),
    ("C-c C-<tab>", "org-cycle-force-archived"),
    ("C-c C-x t", "org-inlinetask-insert-task"),
    ("C-c C-x C-e", "org-clock-modify-effort-estimate"),
    ("C-c C-x I", "org-info-find-node"),
    ("C-c C-x [", "org-reftex-citation"),
    ("C-c C-x @", "org-cite-insert"),
    ("C-c C-x G", "org-feed-goto-inbox"),
    ("C-c C-x g", "org-feed-update-all"),
    ("C-c C-x !", "org-reload"),
    ("C-c C-x C-c", "org-columns"),
    ("C-c C-x ,", "org-timer-pause-or-continue"),
    ("C-c C-x ;", "org-timer-set-timer"),
    ("C-c C-x _", "org-timer-stop"),
    ("C-c C-x 0", "org-timer-start"),
    ("C-c C-x -", "org-timer-item"),
    ("C-c C-x .", "org-timer"),
    ("C-c C-x o", "org-toggle-ordered-property"),
    ("C-c C-x E", "org-inc-effort"),
    ("C-c C-x e", "org-set-effort"),
    ("C-c C-x P", "org-set-property-and-value"),
    ("C-c C-x p", "org-set-property"),
    ("C-c C-x C-r", "org-toggle-radio-button"),
    ("C-c C-x C-b", "org-toggle-checkbox"),
    ("C-c C-x \\", "org-toggle-pretty-entities"),
    ("C-c C-x C-v", "org-link-preview"),
    ("C-c C-x C-l", "org-latex-preview"),
    ("C-c C-x C-u", "org-dblock-update"),
    ("C-c C-x x", "org-dynamic-block-insert-dblock"),
    ("C-c C-x C-d", "org-clock-display"),
    ("C-c C-x C-q", "org-clock-cancel"),
    ("C-c C-x C-j", "org-clock-goto"),
    ("C-c C-x C-o", "org-clock-out"),
    ("C-c C-x C-z", "org-resolve-clocks"),
    ("C-c C-x C-x", "org-clock-in-last"),
    ("C-c C-x TAB", "org-clock-in"),
    ("C-c C-x C-t", "org-toggle-timestamp-overlays"),
    ("C-c C-x C-y", "org-paste-special"),
    ("C-c C-x C-M-v", "org-link-preview-refresh"),
    ("C-c C-x M-w", "org-copy-special"),
    ("C-c C-x C-w", "org-cut-special"),
    ("C-c C-x f", "org-footnote-action"),
    ("C-c C-x C-f", "org-emphasize"),
    ("C-c C-x >", "org-agenda-remove-restriction-lock"),
    ("C-c C-x <", "org-agenda-set-restriction-lock"),
    ("C-c C-x C-p", "org-previous-link"),
    ("C-c C-x C-n", "org-next-link"),
    ("C-c C-x v", "org-copy-visible"),
    ("C-c C-x q", "org-toggle-tags-groups"),
    ("C-c C-x b", "org-tree-to-indirect-buffer"),
    ("C-c C-x A", "org-archive-to-archive-sibling"),
    ("C-c C-x a", "org-toggle-archive-tag"),
    ("C-c C-x C-a", "org-archive-subtree-default"),
    ("C-c C-x C-s", "org-archive-subtree"),
    ("C-c C-x <left>", "org-shiftcontrolleft"),
    ("C-c C-x <right>", "org-shiftcontrolright"),
    ("C-c C-x D", "org-shiftmetadown"),
    ("C-c C-x U", "org-shiftmetaup"),
    ("C-c C-x R", "org-shiftmetaright"),
    ("C-c C-x L", "org-shiftmetaleft"),
    ("C-c C-x d", "org-insert-drawer"),
    ("C-c C-x u", "org-metaup"),
    ("C-c C-x r", "org-metaright"),
    ("C-c C-x l", "org-metaleft"),
    ("C-c C-x RET", "org-meta-return"),
    ("C-c C-x s", "org-insert-structure-template"),
    ("C-c C-x M", "org-insert-todo-heading"),
    ("C-c C-x m", "org-meta-return"),
    ("C-c C-x c", "org-clone-subtree-with-time-shift"),
    ("C-c M-o", "outline-find-headings"),
    ("C-c C->", "org-demote-subtree"),
    ("C-c C-<", "org-promote-subtree"),
    ("C-c C-u", "org-up-heading"),
    ("C-c C-p", "org-previous-visible-heading"),
    ("C-c C-n", "org-next-visible-heading"),
];

pub const AGENDA_MAP: &[(&str, &str)] = &[
    ("K", "org-habit-toggle-display-in-agenda"),
    ("?", "org-agenda-show-the-flagging-note"),
    (";", "org-timer-set-timer"),
    ("^", "org-agenda-filter-by-top-headline"),
    ("<", "org-agenda-filter-by-category"),
    ("~", "org-agenda-limit-interactively"),
    ("|", "org-agenda-filter-remove-all"),
    ("/", "org-agenda-filter"),
    ("=", "org-agenda-filter-by-regexp"),
    ("_", "org-agenda-filter-by-effort"),
    ("\\", "org-agenda-filter-by-tag"),
    ("}", "org-agenda-manipulate-query-subtract-re"),
    ("{", "org-agenda-manipulate-query-add-re"),
    ("]", "org-agenda-manipulate-query-subtract"),
    ("[", "org-agenda-manipulate-query-add"),
    ("b", "org-agenda-earlier"),
    ("f", "org-agenda-later"),
    ("S-<down>", "org-agenda-priority-down"),
    ("S-<up>", "org-agenda-priority-up"),
    ("-", "org-agenda-priority-down"),
    ("+", "org-agenda-priority-up"),
    ("J", "org-agenda-clock-goto"),
    ("X", "org-agenda-clock-cancel"),
    ("O", "org-agenda-clock-out"),
    ("I", "org-agenda-clock-in"),
    ("H", "org-agenda-holidays"),
    ("h", "org-agenda-holidays"),
    ("S", "org-agenda-sunrise-sunset"),
    ("M", "org-agenda-phases-of-moon"),
    ("C", "org-agenda-convert-date"),
    ("c", "org-agenda-goto-calendar"),
    ("i", "org-agenda-diary-entry"),
    (",", "org-agenda-priority"),
    ("<up>", "org-agenda-previous-line"),
    ("C-p", "org-agenda-previous-line"),
    ("<down>", "org-agenda-next-line"),
    ("C-n", "org-agenda-next-line"),
    ("P", "org-agenda-previous-item"),
    ("N", "org-agenda-next-item"),
    ("p", "org-agenda-previous-line"),
    ("n", "org-agenda-next-line"),
    ("T", "org-agenda-show-tags"),
    ("s", "org-save-all-org-buffers"),
    ("x", "org-agenda-exit"),
    ("Q", "org-agenda-Quit"),
    ("q", "org-agenda-quit"),
    ("e", "org-agenda-set-effort"),
    ("g", "org-agenda-redo-all"),
    ("r", "org-agenda-redo"),
    ("G", "org-agenda-toggle-time-grid"),
    ("!", "org-agenda-toggle-deadlines"),
    ("D", "org-agenda-toggle-diary"),
    ("v", "org-agenda-view-mode-dispatch"),
    ("l", "org-agenda-log-mode"),
    ("E", "org-agenda-entry-text-mode"),
    ("R", "org-agenda-clockreport-mode"),
    ("F", "org-agenda-follow-mode"),
    ("0", "digit-argument"),
    ("9", "digit-argument"),
    ("8", "digit-argument"),
    ("7", "digit-argument"),
    ("6", "digit-argument"),
    ("5", "digit-argument"),
    ("4", "digit-argument"),
    ("3", "digit-argument"),
    ("2", "digit-argument"),
    ("1", "digit-argument"),
    (">", "org-agenda-date-prompt"),
    ("S-<left>", "org-agenda-do-date-earlier"),
    ("S-<right>", "org-agenda-do-date-later"),
    ("z", "org-agenda-add-note"),
    ("y", "org-agenda-year-view"),
    ("w", "org-agenda-week-view"),
    ("d", "org-agenda-day-view"),
    ("j", "org-agenda-goto-date"),
    (".", "org-agenda-goto-today"),
    (":", "org-agenda-set-tags"),
    ("a", "org-agenda-archive-default-with-confirmation"),
    ("t", "org-agenda-todo"),
    ("L", "org-agenda-recenter"),
    ("o", "delete-other-windows"),
    ("C-S-<left>", "org-agenda-todo-previousset"),
    ("C-S-<right>", "org-agenda-todo-nextset"),
    ("DEL", "org-agenda-show-scroll-down"),
    ("<backspace>", "org-agenda-show-scroll-down"),
    ("SPC", "org-agenda-show-and-scroll-up"),
    ("$", "org-agenda-archive"),
    ("A", "org-agenda-append-agenda"),
    ("k", "org-agenda-capture"),
    ("B", "org-agenda-bulk-action"),
    ("U", "org-agenda-bulk-unmark-all"),
    ("u", "org-agenda-bulk-unmark"),
    ("%", "org-agenda-bulk-mark-regexp"),
    ("#", "org-agenda-dim-blocked-tasks"),
    ("*", "org-agenda-bulk-mark-all"),
    ("M-*", "org-agenda-bulk-toggle-all"),
    ("M-m", "org-agenda-bulk-toggle"),
    ("m", "org-agenda-bulk-mark"),
    ("M-<up>", "org-agenda-drag-line-backward"),
    ("M-<down>", "org-agenda-drag-line-forward"),
    ("C-c C-c", "org-agenda-ctrl-c-ctrl-c"),
    ("C-c ,", "org-agenda-priority"),
    ("C-c C-p", "org-agenda-previous-date-line"),
    ("C-c C-n", "org-agenda-next-date-line"),
    ("C-c C-a", "org-attach"),
    ("C-c C-d", "org-agenda-deadline"),
    ("C-c C-s", "org-agenda-schedule"),
    ("C-c C-z", "org-agenda-add-note"),
    ("C-c C-q", "org-agenda-set-tags"),
    ("C-c C-t", "org-agenda-todo"),
    ("C-c C-o", "org-agenda-open-link"),
    ("C-c $", "org-agenda-archive"),
    ("C-c C-x I", "org-info-find-node"),
    ("C-c C-x RET p", "org-mobile-push"),
    ("C-c C-x RET g", "org-mobile-pull"),
    ("C-c C-x _", "org-timer-stop"),
    ("C-c C-x <", "org-agenda-set-restriction-lock-from-agenda"),
    ("C-c C-x >", "org-agenda-remove-restriction-lock"),
    ("C-c C-x C-c", "org-agenda-columns"),
    ("C-c C-x <down>", "org-agenda-priority-down"),
    ("C-c C-x <up>", "org-agenda-priority-up"),
    ("C-c C-x C-j", "org-clock-goto"),
    ("C-c C-x C-x", "org-agenda-clock-cancel"),
    ("C-c C-x C-o", "org-agenda-clock-out"),
    ("C-c C-x TAB", "org-agenda-clock-in"),
    ("C-c C-x p", "org-agenda-set-property"),
    ("C-c C-x C-e", "org-clock-modify-effort-estimate"),
    ("C-c C-x e", "org-agenda-set-effort"),
    ("C-c C-x <left>", "org-agenda-do-date-earlier"),
    ("C-c C-x <right>", "org-agenda-do-date-later"),
    ("C-c C-x b", "org-agenda-tree-to-indirect-buffer"),
    ("C-c C-x C-s", "org-agenda-archive"),
    ("C-c C-x A", "org-agenda-archive-to-archive-sibling"),
    ("C-c C-x a", "org-agenda-toggle-archive-tag"),
    ("C-c C-x C-a", "org-agenda-archive-default"),
    ("C-c C-x !", "org-reload"),
    ("C-c C-w", "org-agenda-refile"),
    ("C-k", "org-agenda-kill"),
    ("RET", "org-agenda-switch-to"),
    ("<tab>", "org-agenda-goto"),
    ("TAB", "org-agenda-goto"),
    ("C-/", "org-agenda-undo"),
    ("<undo>", "org-agenda-undo"),
    ("s-z", "org-agenda-undo"),
    ("C-_", "org-agenda-undo"),
    ("C-x C-s", "org-save-all-org-buffers"),
    ("C-x C-w", "org-agenda-write"),
    ("C-x u", "org-agenda-undo"),
];

pub const COLUMNS_MAP: &[(&str, &str)] = &[
    ("M-S-<left>", "org-columns-delete"),
    ("M-S-<right>", "org-columns-new"),
    ("M-<up>", "org-columns-move-row-up"),
    ("M-<down>", "org-columns-move-row-down"),
    ("M-<left>", "org-columns-move-left"),
    ("M-<right>", "org-columns-move-right"),
    (">", "org-columns-widen"),
    ("<", "org-columns-narrow"),
    ("p", "org-columns-previous-allowed-value"),
    ("S-<left>", "org-columns-previous-allowed-value"),
    ("n", "org-columns-next-allowed-value"),
    ("S-<right>", "org-columns-next-allowed-value"),
    ("<down>", "org-columns-move-down"),
    ("<up>", "org-columns-move-up"),
    ("<right>", "forward-char"),
    ("s", "org-columns-edit-attributes"),
    ("a", "org-columns-edit-allowed"),
    ("M-f", "forward-char"),
    ("M-b", "backward-char"),
    ("<left>", "backward-char"),
    ("g", "org-columns-redo"),
    ("r", "org-columns-redo"),
    ("q", "org-columns-quit"),
    ("v", "org-columns-show-value"),
    ("C-c C-o", "org-columns-open-link"),
    ("C-c C-c", "org-columns-toggle-or-columns-quit"),
    ("C-c C-t", "org-columns-todo"),
    ("e", "org-columns-edit-value"),
    ("o", "org-overview"),
    ("?", "org-columns-help-quick-toggle"),
    ("c", "org-columns-content"),
];

pub const CAPTURE_MAP: &[(&str, &str)] = &[
    ("C-c C-w", "org-capture-refile"),
    ("C-c C-k", "org-capture-kill"),
    ("C-c C-c", "org-capture-finalize"),
];

pub const SRC_MAP: &[(&str, &str)] = &[
    ("C-x C-s", "org-edit-src-save"),
    ("C-c C-k", "org-edit-src-abort"),
    ("C-c '", "org-edit-src-exit"),
];
